[pythonproject10-HSnnPtVC]
minor = "3.13"
patch = "3.13.1"

[home-work-poetry-8MD_xVBh]
minor = "3.13"
patch = "3.13.1"

[pythonproject11-oP3_YBOn]
minor = "3.13"
patch = "3.13.1"

[pythonproject12-zjypv8g-]
minor = "3.13"
patch = "3.13.1"

[pythonproject13-CKTUhXc7]
minor = "3.13"
patch = "3.13.1"
